
# case: A docker container calls other exposed container via gateway interface, using public DNS hostname
- when: firewall_whitelist_local_network_addresses|bool and firewall_interface
  include: firewall/allow-incoming-local-connections.yml
  loop_control:
      loop_var: "port"
  loop: "{{ firewall_allowed_outgoing_ports }}"

- name: Allow all incoming connections (for deployment time)
  become: yes
  ufw:
    state: enabled
    direction: incoming
    policy: allow
    interface: "{{ firewall_interface }}"

- name: Whitelist selected incoming ports
  become: yes
  ufw:
    rule: allow
    port: "{{ item }}"
    direction: in
    comment: "Managed by Ansible"
    interface: "{{ firewall_interface }}"
  with_items: "{{ firewall_allowed_outgoing_ports }}"

- name: Deny all incoming connections (except whitelisted ones)
  become: yes
  ufw:
    state: enabled
    direction: incoming
    policy: deny
    interface: "{{ firewall_interface }}"

- name: Allow all outgoing connections
  become: yes
  ufw:
    state: enabled
    direction: outgoing
    policy: allow
    interface: "{{ firewall_interface }}"
