- name: Apply sshd configuration
  become: yes
  template:
      src: "{{ item }}.j2"
      dest: "/{{ item }}"
  with_items:
      - etc/ssh/sshd_config
      - etc/issue
      - etc/motd

- name: Enable sshd on system startup
  become: yes
  systemd:
      name: ssh
      enabled: yes
      state: restarted

- name: Include port change
  set_fact:
    ansible_port: "{{ ssh_input_port }}"
