
- name: Copy helper scripts to the bin directory
  become: yes
  copy:
      src: "../files/usr/local/bin/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: a+x
  with_items:
      - scan-and-strip-logs.py
      - strip-ipv4-address.py

- name: Schedule logs stripping on every hour
  become: yes
  cron:
      name: "logs-ipv4-strip"
      minute: "{{ anonymize_logs_schedule['minute'] | default('00') }}"
      hour: "{{ anonymize_logs_schedule['hour'] | default('*/6') }}"
      day: "{{ anonymize_logs_schedule['day'] | default('*') }}"
      weekday: "{{ anonymize_logs_schedule['weekday'] | default('*') }}"
      month: "{{ anonymize_logs_schedule['month'] | default('*') }}"
      job: "python /usr/local/bin/scan-and-strip-logs.py"
